### ISSUE TITLE
Similar project in English Morningstar data

### ISSUE THREAD

**Issue by datatalking** [jackluson/fund-morning-star-crawler#10]
We are doing a very similar project and wanted to know about collaborating with your team, are you able to scrape data from MorningStar or is this using the paid API?

我们正在做一个非常类似的项目，想知道如何与您的团队合作，您是否能够从晨星中抓取数据，还是使用付费API？

**Comment by jackluson** [comment]
is this site -- https://www.morningstar.com ?

**Comment by jackluson** [comment]
> We are doing a very similar project and wanted to know about collaborating with your team, are you able to scrape data from MorningStar or is this using the paid API?
> 
> 我们正在做一个非常类似的项目，想知道如何与您的团队合作，您是否能够从晨星中抓取数据，还是使用付费API？

 is this site -- https://www.morningstar.com ?

**Comment by datatalking** [comment]
Yes, that is the site api which is still working but data access is limited via api. But is that where you get your data from or is there an overseas location where you get data?

**Comment by jackluson** [comment]
> Yes, that is the site api which is still working but data access is limited via api. But is that where you get your data from or is there an overseas location where you get data?

the repo code is based on [https://www.morningstar.cn/main/default.aspx](https://www.morningstar.cn/main/default.aspx) -- the site is target to  chinese user . if you want to get data from [https://www.morningstar.com](https://www.morningstar.com), i can help you

**Comment by datatalking** [comment]
@jackluson Yes I have access and can scrape or use the API for the next 7 days.

**Comment by datatalking** [comment]
> > Yes, that is the site api which is still working but data access is limited via api. But is that where you get your data from or is there an overseas location where you get data?
> 
> the repo code is based on https://www.morningstar.cn/main/default.aspx -- the site is target to chinese user . if you want to get data from https://www.morningstar.com, i can help you

I would like that help very much, also are there any options to have multiple languages for the text in the code. The Mandarin you wrote I can begin to translate into English, confirm its correct by sending you PR which I hope are accepted?

**Comment by jackluson** [comment]
> 
welcome your PR

**Comment by datatalking** [comment]
> > 
> 
> welcome your PR

I should have a few dozen lines translated this weekend and will submit the PR.

How does it work with multiple languages in GitHub does my English translation override your Mandarin or is there a dual language option?

**Comment by datatalking** [comment]
PR submitted, please let me know if that will work or if you have a different preference.

1. I noticed my merge did work but the files I deleted should not be deleted from your repo, just mine and I will resync those back to my repo.
2. I updated the PR to just the main.py file
3. Will work on the rest over time

**Comment by jackluson** [comment]
> PR submitted, please let me know if that will work or if you have a different preference.
> 
> 1. I noticed my merge did work but the files I deleted should not be deleted from your repo, just mine and I will resync those back to my repo.
> 2. I updated the PR to just the main.py file
> 3. Will work on the rest over time

I misunderstood the mean you mentioned befored -- I thinked  you just want to submit PR for Readme.md

**Comment by datatalking** [comment]
Is it ok to keep parsing the code from Mandarin to English? :)

I can also parse the README.md to English later today.

**Comment by jackluson** [comment]
> Is it ok to keep parsing the code from Mandarin to English? :) I can also parse the README.md to English later today.
> […](#)
> Sent from my iPhone
> On Dec 4, 2022, at 8:36 AM, camel lu ***@***.***> wrote: ﻿ PR submitted, please let me know if that will work or if you have a different preference. I noticed my merge did work but the files I deleted should not be deleted from your repo, just mine and I will resync those back to my repo. I updated the PR to just the main.py file Will work on the rest over time I misunderstood the mean you mentioned befored -- I thinked you just want to submit PR for Readme.md — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

I don't recommend translating the main file, because it will overwrite the original code, but the readme can keep both Chinese and English versions.
