### ISSUE TITLE
关于cookie的获取问题

### ISSUE THREAD

**Issue by imoyao** [jackluson/fund-morning-star-crawler#11]
根据readme中说明，登录方式有两种：
1. 借助selenium使用账户信息登录
2. 直接赋值`login_cookie` 

 https://github.com/jackluson/fund-morning-star-crawler/blob/02072bc7575d5f4a71aebabf1e2a266edaa4801a/.env.example#L3

关于cookie的获取方法，readme中没有看到相关的说明，请教一下是否可以补充相关说明？感谢

**Comment by imoyao** [comment]
从另一个项目看到如下描述：

> 直接copy请求头的cookie字段值覆盖.env的login_cookie即可

目前运行结果为：
![image](https://user-images.githubusercontent.com/22978431/182832166-6409fc24-5773-4816-869c-dcbd2e3ba7cc.png)

数据库中也没有存储相关数据

**Comment by jackluson** [comment]
> 从另一个项目看到如下描述：
> 
> > 直接copy请求头的cookie字段值覆盖.env的login_cookie即可
> 
> 目前运行结果为： ![image](https://user-images.githubusercontent.com/22978431/182832166-6409fc24-5773-4816-869c-dcbd2e3ba7cc.png)
> 
> 数据库中也没有存储相关数据

直接打开浏览器开发者工具copy请求头的cookie即可

**Comment by imoyao** [comment]
好的，cookie获取问题已经解决
