### ISSUE TITLE
Data access question

### ISSUE THREAD

**Issue by datatalking** [jackluson/fund-morning-star-crawler#12]
In your README.md section 3 you state "Change the environment variable value according to your own situation, such as Morningstar username, password, execute specific crawler script"

Does this mean its an option to have an account at morningstar.com or you 100% need a paid morning star account to run or use your code?

**Comment by jackluson** [comment]
> In your README.md section 3 you state "Change the environment variable value according to your own situation, such as Morningstar username, password, execute specific crawler script"
> 
> Does this mean its an option to have an account at morningstar.com or you 100% need a paid morning star account to run or use your code?

it need an account at morningstar.com, but not need pay

**Comment by datatalking** [comment]
I have downloaded it, patched most of the language difference but even though I have downloaded and run `./chromedriver` and the file shows its there `port:9515` it still says its not in PATH... at root of project? Ideas?

**Comment by jackluson** [comment]
> I have downloaded it, patched most of the language difference but even though I have downloaded and run `./chromedriver` and the file shows its there `port:9515` it still says its not in PATH... at root of project? Ideas?

why does it have the `port:9515` ?  could you show me the code and is your code  based on my？

**Comment by datatalking** [comment]
@jackluson I've been able to rerun the code and I guess a restart was in order so the 'port:9515' seems to have resolved itself.

I will have to look at the option of translating a chunk of this from Madarin to English but Google Translate is helping.

That being said there is two different but related issues:
1. When I do run 'acquire_fund_snapshot.py' and I populate the 'db_name' in the .env file it can't find it which is weird becasue my ide ran a test and it can query it. Do I have to enable an option or what did I miss
2. When I don't populate the 'db_name' variable with the dbname I'm using and I run the 'acquire_fund_snapshot.py' you reccomend I get the below error

```
Traceback (most recent call last):
  File "/Users/username/fund-morning-star-crawler/src/acquire_fund_snapshot.py", line 166, in <module>
    fund_list = get_fund_list(page_index)
  File "/Users/username/fund-morning-star-crawler/src/acquire_fund_snapshot.py", line 66, in get_fund_list
    '/html/body/form/div[8]/div/div[4]/div[3]/div[2]/span').text) / page_count)
  File "/Users/username/opt/anaconda3/envs/fund-morning-star-crawler/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/username/opt/anaconda3/envs/fund-morning-star-crawler/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/username/opt/anaconda3/envs/fund-morning-star-crawler/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/username/opt/anaconda3/envs/fund-morning-star-crawler/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/form/div[8]/div/div[4]/div[3]/div[2]/span"}
  (Session info: headless chrome=107.0.5304.110)
```
I believe I've followed your instructions and have the 'chromedriver' in the root project folder? Selenium and chrome are new to me.
<img width="443" alt="Screen Shot 2022-11-17 at 9 11 02 PM" src="https://user-images.githubusercontent.com/11813209/202624465-378bb909-800c-40e7-acc2-f655ed2b8cdc.png">

**Comment by datatalking** [comment]
> > I have downloaded it, patched most of the language difference but even though I have downloaded and run `./chromedriver` and the file shows its there `port:9515` it still says its not in PATH... at root of project? Ideas?
> 
> why does it have the `port:9515` ? could you show me the code and is your code based on my？

I was able to reproduce this by loading what I think is the `chromedriver` into the local root of the project and this is the error that comes up
![322FA4B3-0FB9-47F6-ABF4-6EDB0027ACAC_4_5005_c](https://user-images.githubusercontent.com/11813209/202881313-6d220653-6627-4788-aa1f-7ecb54484c08.jpeg)

**Comment by jackluson** [comment]
> @jackluson I've been able to rerun the code and I guess a restart was in order so the 'port:9515' seems to have resolved itself.
> 
> I will have to look at the option of translating a chunk of this from Madarin to English but Google Translate is helping.
> 
> That being said there is two different but related issues:
> 
> 1. When I do run 'acquire_fund_snapshot.py' and I populate the 'db_name' in the .env file it can't find it which is weird becasue my ide ran a test and it can query it. Do I have to enable an option or what did I miss
> 2. When I don't populate the 'db_name' variable with the dbname I'm using and I run the 'acquire_fund_snapshot.py' you reccomend I get the below error
> 
> ```
> Traceback (most recent call last):
>   File "/Users/username/fund-morning-star-crawler/src/acquire_fund_snapshot.py", line 166, in <module>
>     fund_list = get_fund_list(page_index)
>   File "/Users/username/fund-morning-star-crawler/src/acquire_fund_snapshot.py", line 66, in get_fund_list
>     '/html/body/form/div[8]/div/div[4]/div[3]/div[2]/span').text) / page_count)
>   File "/Users/username/opt/anaconda3/envs/fund-morning-star-crawler/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
>     return self.find_element(by=By.XPATH, value=xpath)
>   File "/Users/username/opt/anaconda3/envs/fund-morning-star-crawler/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
>     'value': value})['value']
>   File "/Users/username/opt/anaconda3/envs/fund-morning-star-crawler/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/Users/username/opt/anaconda3/envs/fund-morning-star-crawler/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/form/div[8]/div/div[4]/div[3]/div[2]/span"}
>   (Session info: headless chrome=107.0.5304.110)
> ```
> 
> I believe I've followed your instructions and have the 'chromedriver' in the root project folder? Selenium and chrome are new to me. <img alt="Screen Shot 2022-11-17 at 9 11 02 PM" width="443" src="https://user-images.githubusercontent.com/11813209/202624465-378bb909-800c-40e7-acc2-f655ed2b8cdc.png">

you need to create your own database which store your data crawled , and that you change `db_name` environment variable as your database name

**Comment by jackluson** [comment]
my twitter username is luxuemin2, you can DM me

**Comment by jackluson** [comment]
> > > I have downloaded it, patched most of the language difference but even though I have downloaded and run `./chromedriver` and the file shows its there `port:9515` it still says its not in PATH... at root of project? Ideas?
> > 
> > 
> > why does it have the `port:9515` ? could you show me the code and is your code based on my？
> 
> I was able to reproduce this by loading what I think is the `chromedriver` into the local root of the project and this is the error that comes up ![322FA4B3-0FB9-47F6-ABF4-6EDB0027ACAC_4_5005_c](https://user-images.githubusercontent.com/11813209/202881313-6d220653-6627-4788-aa1f-7ecb54484c08.jpeg)

my twitter username is luxuemin2, you can DM me

**Comment by datatalking** [comment]
In addition I tried to run the code from the chromium page.

```
import time

from selenium import webdriver
from selenium.webdriver.chrome.service import Service

service = Service('<inserted my path>')
service.start()
driver = webdriver.Remote(service.service_url)
driver.get('http://www.google.com/');
time.sleep(5) # Let the user actually see something!
driver.quit()
```
![46DFAC3C-315B-4DFC-8C0F-CE386A35054B_4_5005_c](https://user-images.githubusercontent.com/11813209/202881987-fb219c17-2c45-42a1-87e9-dcd7390aba89.jpeg)

**Comment by datatalking** [comment]
> In addition I tried to run the code from the chromium page.
> 
> 
> 
> ```
> 
> import time
> 
> 
> 
> from selenium import webdriver
> 
> from selenium.webdriver.chrome.service import Service
> 
> 
> 
> service = Service('<inserted my path>')
> 
> service.start()
> 
> driver = webdriver.Remote(service.service_url)
> 
> driver.get('http://www.google.com/');
> 
> time.sleep(5) # Let the user actually see something!
> 
> driver.quit()
> 
> ```
> 
> ![46DFAC3C-315B-4DFC-8C0F-CE386A35054B_4_5005_c](https://user-images.githubusercontent.com/11813209/202881987-fb219c17-2c45-42a1-87e9-dcd7390aba89.jpeg)
> 
> 

@jackluson Any update or suggestions on the errors I'm facing with the code?

**Comment by jackluson** [comment]
> 
I see it is normal. Has it any error above?

**Comment by jackluson** [comment]
> > 
> 
> I see it is normal. Has it any error above?

**Comment by jackluson** [comment]
> > In addition I tried to run the code from the chromium page.
> > ```
> > 
> > import time
> > 
> > 
> > 
> > from selenium import webdriver
> > 
> > from selenium.webdriver.chrome.service import Service
> > 
> > 
> > 
> > service = Service('<inserted my path>')
> > 
> > service.start()
> > 
> > driver = webdriver.Remote(service.service_url)
> > 
> > driver.get('http://www.google.com/');
> > 
> > time.sleep(5) # Let the user actually see something!
> > 
> > driver.quit()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![46DFAC3C-315B-4DFC-8C0F-CE386A35054B_4_5005_c](https://user-images.githubusercontent.com/11813209/202881987-fb219c17-2c45-42a1-87e9-dcd7390aba89.jpeg)
> 
> @jackluson Any update or suggestions on the errors I'm facing with the code?

I see it is normal. Has it any error above?

**Comment by datatalking** [comment]
@jackluson 
1. The error when I run `main.py` which really isn't an error is that it says "only local connections allowed", then the script ends. Should 'only local connections' be setup or what is that for?
2. The other error is when I do sidestep this error and I try to run `acquire_fund_snapshot.py`, `acquire_fund_base.py`, or `acquire_fund_quarter.py` they all generate the same error. Is there a trick with mysql to enable access or a password default in the instructions I missed?
```
  pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
```

**Comment by datatalking** [comment]
@jackluson
1. I dug into the code this morning, started over again and made progress to get a new mySQL database up and running which worked... until it went to access the `chromedriver` which is in the local folder gave me this list of errors.
2. I did get a `security permission required` popup on my machine which I allowed, still it finds issues with `acquire_fund_snapshot.py` line 63, get_fund_list after being called by line 167. See attached photo. If possible let me know if this could be easier with a video chat. FaceTime, Zoom or Telegram are options.
![Image 12-8-22 at 1 50 PM](https://user-images.githubusercontent.com/11813209/206577376-61cba78d-cc34-43fb-b37a-ad7df07cb044.jpg)
3. Could there be a setting I missed or should I be accessing the site since its domestic for me and from overseas you might be accessing a different link?

**Comment by datatalking** [comment]
@jackluson Checking in on access to the data from Morningstar; I'm still not able to access it via the code in the repository. Could we chat somehow? I know Bejing is about +14 from Seattle timezone.

**Comment by jackluson** [comment]
> 

sorry，it so late for reply you, because i got contracted covid-19 a week ago. you can contact me by twitter, my username is 'luxuemin2'

**Comment by jackluson** [comment]
> @jackluson Checking in on access to the data from Morningstar; I'm still not able to access it via the code in the repository. Could we chat somehow? I know Bejing is about +14 from Seattle timezone.

sorry，it so late for replying you, because i got contracted covid-19 a week ago. you can contact me by twitter, my username is 'luxuemin2'
